### ISSUE TITLE
Fix entity search results

### ISSUE THREAD

**Issue by bmenn** [anidata/ht-archive#3]
Entity search result data seems to disagree with results from manually querying the SQL database.

Tasks:
- [x] Identify source of the bug
- [ ] Make the fix

**Comment by coxjonc** [comment]
I'm working on getting this project running on my local machine and once I have it working I'd be happy to look into this - go ahead and assign me if no one else is working on this issue

**Comment by coxjonc** [comment]
If you don't mind could you give an example of a query that returns a different result in the app vs. querying the database directly?

**Comment by bmenn** [comment]
@geezhawk,

Example for debugging.

Entity id 574 has four unique phone numbers:
```
SELECT DISTINCT number
FROM BackpageEntities be
JOIN BackpagePhone bp
    ON be.BackpagePostId = bp.BackpagePostId
WHERE be.entity_id = 574;
```

When using the `770-xxx-xxxx` number returned from the query on the "Entity Resolution" page, only one phone number is displayed.

Log of the suspect query being run:
```
SELECT backpageentities.entity_id::integer AS id, ARRAY_TO_STRING(ARRAY_AGG(DISTINCT backpagephone.number), ', ') as phone, ARRAY_TO_STRING(ARRAY_AGG(DISTINCT backpageemail.name), ', ') as email, COUNT(DISTINCT backpageentities.backpagepostid) postCount FROM backpageentities LEFT JOIN backpageemail ON backpageentities.backpagepostid::integer = backpageemail.backpagepostid LEFT JOIN backpagephone ON backpageentities.backpagepostid::integer = backpagephone.backpagepostid WHERE backpageemail.name = ANY('{""}'::text[]) OR backpagephone.number = ANY('{"770-xxx-xxxx"}'::text[]) GROUP BY backpageentities.entity_id;
```

**Comment by coxjonc** [comment]
Thanks man. I'll try and see what's going on.

**Comment by bmenn** [comment]
:+1: Thanks for helping out!

**Comment by coxjonc** [comment]
Found the issue. There are some issues with the SQL query that is generated by `QueryHandler` for the phone number you gave me, specifically the `WHERE bp.number = ANY('{"770-xxx-xxxx"'})` clause. Filtering the query result by cases where the phone number matches will filter out rows with other phone numbers, even if those numbers are matched to the `entity_id`.

To get the full list of phone numbers for a specified entity, you have to filter by `entity_id` instead of by phone number

Here's my proposed solution: I suggest that we split the searchEntities SQL query into two queries - one to get the `entity_id` or `entity_id`s that are associated with a given phone number / email address. The next query will run as a callback when the first returns successfully, and it will return the JSON response with the email addresses, phone numbers, and posts associated with the entity_id.

If that sounds OK I'll hack something together when I can.

**Comment by bmenn** [comment]
Good find. That sounds like the best fix, especially as the the BackpageEntities table grows.
